name: packages_extensions
description: Extensions for non Dart core packages.
version: 0.1.2
homepage: https://github.com/giorgiofran/packages_extensions.git

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  decimal: ^3.0.0
  rational: ^2.0.0
  power_extensions: ^0.2.0

dev_dependencies:
  lints: 6.1.0
  test: ^1.16.0
